M48
; DRILL file {KiCad 8.0.3} date 2024-06-22T22:44:29-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-22T22:44:29-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.7343Y-3.1062
X4.7343Y-3.5562
X6.3622Y-3.0934
X6.3622Y-3.5434
M30
